services:
  postgres:
    image: postgres:15-alpine
    container_name: event-platform-db
    environment:
      POSTGRES_USER: eventadmin
      POSTGRES_PASSWORD: "Dbn8j6kB#"
      POSTGRES_DB: eventplatform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:3
    container_name: event-platform-localstack
    environment:
      SERVICES: sqs
      DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  postgres_data:
  localstack_data: